### PR TITLE
fix(#901): change VillagerType/VillagerProffesion/FrogVariant/CatType enums to registry

### LINKED ISSUE #901: Could not load 'plugins/Shopkeepers-2.22.1.jar'
## Preliminaries:

* **Shopkeepers version:** `2.22.1`
* **Spigot version:** `4267-Spigot-5bbef5a-403accd (MC: 1.21) (Implementing API version 1.21-R0.1-SNAPSHOT)`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`able`** to reproduce my issue on a freshly set up and up-to-date Spigot server (currently **`4267-Spigot-5bbef5a-403accd (MC: 1.21) (Implementing API version 1.21-R0.1-SNAPSHOT)`**) with the latest version of Shopkeepers (currently **`2.22.1`**), with no other plugins and with no kinds of other server or client mods.

### Description of the issue.
When starting the server, as mentioned in the title, an error message along with several stack traces and races is output, and the plugin is not enabled.

### Step-by-step instructions on how to reproduce the issue.
1. Create a new folder.
2. Place `spigot-1.21.jar` and `eula.txt` in the folder.
3. Create a `plugins` folder and place `Shopkeepers-2.22.1.jar` in it.
4. Run `java -jar spigot-1.21.jar -nogui`.

### Observed behavior.
Refer to the server logs. The `/plugins` command outputs `Plugins (0):`.

### Expected behavior.
The plugin should be enabled.

### Server logs (from server startup until issue). Consider enabling debug mode in the config for additional console output.

```
Starting server
Loading libraries, please wait...
[11:02:55] [ServerMain/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[11:02:55] [ServerMain/INFO]: Found new data pack file/bukkit, loading it automatically
[11:02:56] [ServerMain/INFO]: No existing world data, creating new world
[11:02:57] [ServerMain/INFO]: Loaded 1290 recipes
[11:02:55] [ServerMain/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[11:02:55] [ServerMain/INFO]: Found new data pack file/bukkit, loading it automatically
[11:02:56] [ServerMain/INFO]: No existing world data, creating new world
[11:02:57] [ServerMain/INFO]: Loaded 1290 recipes
[11:02:59] [Server thread/INFO]: Starting minecraft server version 1.21
[11:02:59] [Server thread/INFO]: Loading properties
[11:02:59] [Server thread/INFO]: This server is running CraftBukkit version 4267-Spigot-5bbef5a-403accd (MC: 1.21) (Implementing API version 1.21-R0.1-SNAPSHOT)
[11:03:00] [Server thread/INFO]: *** This version of Spigot contains changes to some enums. If you notice that plugins no longer work after updating, please report this to the developers of those plugins first. ***
[11:03:00] [Server thread/INFO]: *** If you cannot update those plugins, you can try setting `settings.compatibility.enum-compatibility-mode` to `true` in `bukkit.yml`. ***
[11:03:00] [Server thread/INFO]: Using 4 threads for Netty based IO
[11:03:00] [Server thread/INFO]: Server Ping Player Sample Count: 12
[11:03:00] [Server thread/INFO]: Debug logging is disabled
[11:03:00] [Server thread/INFO]: Default game type: SURVIVAL
[11:03:00] [Server thread/INFO]: Generating keypair
[11:03:00] [Server thread/INFO]: Starting Minecraft server on *:25565
[11:03:00] [Server thread/INFO]: Using epoll channel type
[11:03:01] [Server thread/ERROR]: Could not load 'plugins/Shopkeepers-2.22.1.jar'
org.bukkit.plugin.InvalidPluginException: Exception initializing main class `com.nisovin.shopkeepers.SKShopkeepersPlugin'
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:96) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:406) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:313) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:122) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.loadPlugins(CraftServer.java:464) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4267-Spigot-5bbef5a-403accd]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:236) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4267-Spigot-5bbef5a-403accd]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4267-Spigot-5bbef5a-403accd]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4267-Spigot-5bbef5a-403accd]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:88) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        ... 9 more
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/nisovin/shopkeepers/shopobjects/living/types/ZombieVillagerShop.cycleProfession(Z)V @8: invokestatic
  Reason:
    Type 'org/bukkit/entity/Villager$Profession' (current frame, stack[2]) is not assignable to 'java/lang/Enum'
  Current Frame:
    bci: @8
    flags: { }
    locals: { 'com/nisovin/shopkeepers/shopobjects/living/types/ZombieVillagerShop', integer }
    stack: { 'com/nisovin/shopkeepers/shopobjects/living/types/ZombieVillagerShop', 'java/lang/Class', 'org/bukkit/entity/Villager$Profession', integer }
  Bytecode:
    0000000: 2a12 092a b600 981b b800 9ec0 0009 b600
    0000010: a0b1

        at com.nisovin.shopkeepers.shopobjects.living.SKLivingShopObjectTypes.createLivingShopObjectType(SKLivingShopObjectTypes.java:410) ~[?:?]
        at com.nisovin.shopkeepers.shopobjects.living.SKLivingShopObjectTypes.createShopObjectTypes(SKLivingShopObjectTypes.java:255) ~[?:?]
        at com.nisovin.shopkeepers.shopobjects.living.SKLivingShopObjectTypes.<init>(SKLivingShopObjectTypes.java:246) ~[?:?]
        at com.nisovin.shopkeepers.shopobjects.living.LivingShops.<init>(LivingShops.java:76) ~[?:?]
        at com.nisovin.shopkeepers.SKShopkeepersPlugin.<init>(SKShopkeepersPlugin.java:156) ~[?:?]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:88) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        ... 9 more
[11:03:02] [Server thread/INFO]: Preparing level "world"
[11:03:02] [Server thread/INFO]: -------- World Settings For [world] --------
[11:03:02] [Server thread/INFO]: View Distance: 10
[11:03:02] [Server thread/INFO]: Simulation Distance: 10
[11:03:02] [Server thread/INFO]: Item Despawn Rate: 6000
[11:03:02] [Server thread/INFO]: Item Merge Radius: 2.5
[11:03:02] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[11:03:02] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[11:03:02] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
...
```

### ... Anything else that might be useful to reproduce and identify the issue.
- No other plugins are installed.

```
java -version
openjdk version "21.0.3" 2024-04-16 LTS
OpenJDK Runtime Environment Corretto-21.0.3.9.1 (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM Corretto-21.0.3.9.1 (build 21.0.3+9-LTS, mixed mode, sharing)
```

```
cat /etc/os-release
NAME="Amazon Linux"
VERSION="2023"
ID="amzn"
ID_LIKE="fedora"
VERSION_ID="2023"
PLATFORM_ID="platform:al2023"
PRETTY_NAME="Amazon Linux 2023"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2023"
HOME_URL="https://aws.amazon.com/linux/"
BUG_REPORT_URL="https://github.com/amazonlinux/amazon-linux-2023"
SUPPORT_END="2028-03-01"
```

### PR DESCRIPTION
**Pull request by DerMistkaefer**
fix #901 

2024-07-06: Spigot changed the (VillagerProfession / VillagerType / FrogVariant / CatType) Enum to a Keyed Type.
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/7983b966630a4224ff7a26e321d2369444d17978#src%2Fmain%2Fjava%2Forg%2Fbukkit%2Fentity%2FVillager.java

This change caused a startup error.

The VillagerProfession / VillagerType has been a Keyed Type since 2019-05-01, which predates the release of minecraft version 1.14.1. Therefore, all versions supported by Shopkeepers (>= 1.16.5) are compatible with this change.

The FrogVariant is Keyed since implementation. But I only changed it in the 1.21 nms.

Now for the complicated part: the CatType has been a Keyed Type since 2023-12-08, corresponding to Minecraft versions 1.20.3/1.20.4. Therefore, I implemented the necessary switch in the NMS modules to accommodate this change.

I easily updated the Serializer. The internal NamespacedKeySerializer checks if a namespace exists; otherwise, it defaults to "minecraft", so no further migration is needed.

Now the server boots without errors.

### CODE REVIEW

**Comment by blablubbabc** [comment]
Thanks.

Since more similar enum related API backwards incompatible changes are expected to come to the API/server in the near future, I am currently in the process of taking this chance and completely drop support for older versions, and update the code base to Java 21 and the latest Bukkit API. But those are some larger changes (also some IDE/tooling related changes on my side that I use for this project).

But I can include these changes in the meantime.

Some notes though:
* When running on an unsupported server version ("compatibility mode"), instead of returning a null cat type serializer, it probably makes sense to either disable the cat type completely, or add a default serializer that retrieves the cat type registry via reflection and disable the cat type when this fails. I don't think null will currently work.
* Without having it tested yet, I am not sure if the NamespacedKeySerializer is able to deserialize the previous upper-case enum names (we might need to lowercase the string before trying to parse it as NamespacedKey). Or we replaced `NamespacedKey.fromString` with our own `NamespacedKeyUtils.parse` helper, which already includes this lowercasing.

**Comment by DerMistkaefer** [comment]
Okay, thanks. I also don't think such a change in an interim version from Spigot is optimal.

But I just wanted to quickly get a working version of Shopkeepers again.

Regarding your comments:

- I couldn't manage to implement the cat type stuff in default mode because the default implementation is always analyzed first, even if it is overridden. Even with try-catch, nothing could be done here. I tried reflection again, and it seems to be working.
- Regarding the `NamespaceKey`, yes, users have already reported problems with it. The implementation of `NamespacedKeyUtils` resolves these issues. Thanks for the remark

**Comment by CatBang** [comment]
> Thanks.
> 
> Since more similar enum related API backwards incompatible changes are expected to come to the API/server in the near future, I am currently in the process of taking this chance and completely drop support for older versions, and update the code base to Java 21 and the latest Bukkit API. But those are some larger changes (also some IDE/tooling related changes on my side that I use for this project).
> 
> But I can include these changes in the meantime.
> 
> Some notes though:
> 
>     * When running on an unsupported server version ("compatibility mode"), instead of returning a null cat type serializer, it probably makes sense to either disable the cat type completely, or add a default serializer that retrieves the cat type registry via reflection and disable the cat type when this fails. I think null might currently crash the plugin in this case.
> 
>     * Without having it tested yet, I am not sure if the NamespacedKeySerializer is able to deserialize the previous upper-case enum names (we might need to lowercase the string before trying to parse it as NamespacedKey). Or we replace `NamespacedKey.fromString` with our own `NamespacedKeyUtils.parse` helper, which already includes this lowercasing.

I agree, shopkeepers are important for many servers, but they currently cannot operate on the newer 1.21 build versions. Should we prioritize making shopkeepers compatible with 1.21 servers before considering other bold actions? Let's avoid an excessively long waiting period.🙏🏼

**Comment by blablubbabc** [comment]
Thanks!

I have made some more minor changes to the handling of the cat type in compatibility mode (https://github.com/Shopkeepers/Shopkeepers/commit/47c96a1a19783215e52eb3707b87a13a4984504d).

**Pull request merged**
